
run:	
		./geffe 10011011 110101011010101010100101010100101011011010101010 10

build:	function.c main.c
	
		gcc -c  main.c function.c function.h
		gcc  main.o function.o -o geffe
	
function: function.c
	
	gcc - c function.c function.h
	
remove : 
	rm -f *.o *.h.gch
	rm -f geffe
	


